list: $/compuflex/faqs/models/answer/columns.yaml
modelClass: Compuflex\Faqs\Models\Answer
title: Answers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'compuflex/faqs/answers/update/:id'
