plugin:
    name: 'compuflex.faqs::lang.plugin.name'
    description: 'compuflex.faqs::lang.plugin.description'
    author: 'Thomas Yamakaitis'
    icon: oc-icon-question-circle
    homepage: 'http://compuflexcorp.com/'
navigation:
    faqs:
        label: 'compuflex.faqs::lang.plugin.name'
        url: compuflex/faqs/questions
        icon: icon-question-circle
        sideMenu:
            questions:
                label: 'compuflex.faqs::lang.menu.questions'
                url: compuflex/faqs/questions
                icon: icon-question
            answers:
                label: 'compuflex.faqs::lang.menu.answers'
                url: compuflex/faqs/answers
                icon: icon-calculator
