title: Companies
modelClass: Compuflex\Company\Models\Company
list: $/compuflex/company/models/company/columns.yaml
recordUrl: 'compuflex/company/companies/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
