list: $/compuflex/contact/models/group/columns.yaml
modelClass: Compuflex\Contact\Models\Group
title: Groups
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'compuflex/contact/groups/update/:id'
