list: $/compuflex/faqs/models/question/columns.yaml
modelClass: Compuflex\Faqs\Models\Question
title: Questions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'compuflex/faqs/questions/update/:id'
